// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconBorrow({
  size = 24,
}: {
  size?: number;
}) {
  return (
    <svg fill="none" viewBox="0 0 24 24" width={size} height={size}>
      <path
        fill="currentColor"
        d="M4.1 13.4c0-2.1 1.7-3.8 3.8-3.8h5.6c1.6 0 2.9 1.3 2.9 2.9v1.2c0 1.6-1.3 2.9-2.9 2.9H7.3c-1.8 0-3.2-1.4-3.2-3.2Z"
      />
      <path
        fill="currentColor"
        d="M13.4 13.2c.5-2 .9-4.3 1.3-6.8.2-1.4 1.4-2.5 2.9-2.5.7 0 1.3.4 1.6 1l.4.8h.7c.9 0 1.6.7 1.6 1.6v.2c0 1.1-.9 2.1-2.1 2.1h-1.9c-.6 0-1.1.4-1.3 1l-.8 3.1-2.4-.5Z"
      />
      <path
        fill="currentColor"
        d="M16.7 4.5 15.5 1.8c-.2-.4.3-.8.6-.5l2 2.1-.5 1.4-.9-.3ZM18.8 4.8l1.5-2.1c.3-.3.8-.1.7.3l-.3 2.5-1.9-.7Z"
      />
      <path
        fill="currentColor"
        d="M5.3 15.4h2.1v5.2c0 .3-.2.5-.5.5H5.8c-.3 0-.5-.2-.5-.5v-5.2ZM9.1 15.8h2v4.8c0 .3-.2.5-.5.5h-1c-.3 0-.5-.2-.5-.5v-4.8ZM13 15.4h2.1l1 5.1c.1.3-.2.6-.5.6h-1c-.2 0-.4-.2-.5-.4L13 15.4Z"
      />
      <path fill="currentColor" d="M4.9 12.1 2.7 10.8c-.4-.2-.2-.8.3-.7l2.4.5-.5 1.5Z" />
    </svg>
  );
}
